package Calculatrice;

/**
* Calculatrice/ServeurCalculatriceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calculatrice.idl
* vendredi 28 mars 2014 16 h 47 CET
*/

public final class ServeurCalculatriceHolder implements org.omg.CORBA.portable.Streamable
{
  public Calculatrice.ServeurCalculatrice value = null;

  public ServeurCalculatriceHolder ()
  {
  }

  public ServeurCalculatriceHolder (Calculatrice.ServeurCalculatrice initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Calculatrice.ServeurCalculatriceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Calculatrice.ServeurCalculatriceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Calculatrice.ServeurCalculatriceHelper.type ();
  }

}
