package cache;


/**
* cache/FileUnknown.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from cache.idl
* vendredi 11 avril 2014 17 h 24 CEST
*/

public final class FileUnknown extends org.omg.CORBA.UserException
{

  public FileUnknown ()
  {
    super(FileUnknownHelper.id());
  } // ctor


  public FileUnknown (String $reason)
  {
    super(FileUnknownHelper.id() + "  " + $reason);
  } // ctor

} // class FileUnknown
