package cache;

/**
* cache/FileUnknownHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from cache.idl
* vendredi 11 avril 2014 17 h 24 CEST
*/

public final class FileUnknownHolder implements org.omg.CORBA.portable.Streamable
{
  public cache.FileUnknown value = null;

  public FileUnknownHolder ()
  {
  }

  public FileUnknownHolder (cache.FileUnknown initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = cache.FileUnknownHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    cache.FileUnknownHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return cache.FileUnknownHelper.type ();
  }

}
