package cache;


/**
* cache/IOError.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from cache.idl
* vendredi 11 avril 2014 17 h 24 CEST
*/

public final class IOError extends org.omg.CORBA.UserException
{

  public IOError ()
  {
    super(IOErrorHelper.id());
  } // ctor


  public IOError (String $reason)
  {
    super(IOErrorHelper.id() + "  " + $reason);
  } // ctor

} // class IOError
