package cache;

/**
* cache/IOErrorHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from cache.idl
* vendredi 11 avril 2014 17 h 24 CEST
*/

public final class IOErrorHolder implements org.omg.CORBA.portable.Streamable
{
  public cache.IOError value = null;

  public IOErrorHolder ()
  {
  }

  public IOErrorHolder (cache.IOError initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = cache.IOErrorHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    cache.IOErrorHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return cache.IOErrorHelper.type ();
  }

}
