package cache;


/**
* cache/ReaderItfPOATie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from cache.idl
* vendredi 11 avril 2014 17 h 24 CEST
*/

public class ReaderItfPOATie extends ReaderItfPOA
{

  // Constructors

  public ReaderItfPOATie ( cache.ReaderItfOperations delegate ) {
      this._impl = delegate;
  }
  public ReaderItfPOATie ( cache.ReaderItfOperations delegate , org.omg.PortableServer.POA poa ) {
      this._impl = delegate;
      this._poa      = poa;
  }
  public cache.ReaderItfOperations _delegate() {
      return this._impl;
  }
  public void _delegate (cache.ReaderItfOperations delegate ) {
      this._impl = delegate;
  }
  public org.omg.PortableServer.POA _default_POA() {
      if(_poa != null) {
          return _poa;
      }
      else {
          return super._default_POA();
      }
  }
  public boolean read (String fileName, org.omg.CORBA.StringHolder data)
  {
    return _impl.read(fileName, data);
  } // read

  public void fileDataOutOfDate (String fileName)
  {
    _impl.fileDataOutOfDate(fileName);
  } // fileDataOutOfDate

  private cache.ReaderItfOperations _impl;
  private org.omg.PortableServer.POA _poa;

} // class ReaderItfPOATie
