package cache;


/**
* cache/ReaderItfOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from cache.idl
* vendredi 11 avril 2014 17 h 24 CEST
*/

public interface ReaderItfOperations 
{
  boolean read (String fileName, org.omg.CORBA.StringHolder data);
  void fileDataOutOfDate (String fileName);
} // interface ReaderItfOperations
