package cache;

/**
* cache/ReaderItfHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from cache.idl
* vendredi 11 avril 2014 17 h 24 CEST
*/

public final class ReaderItfHolder implements org.omg.CORBA.portable.Streamable
{
  public cache.ReaderItf value = null;

  public ReaderItfHolder ()
  {
  }

  public ReaderItfHolder (cache.ReaderItf initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = cache.ReaderItfHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    cache.ReaderItfHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return cache.ReaderItfHelper.type ();
  }

}
