package cache;

/**
* cache/ServerItfHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from cache.idl
* vendredi 11 avril 2014 17 h 24 CEST
*/

public final class ServerItfHolder implements org.omg.CORBA.portable.Streamable
{
  public cache.ServerItf value = null;

  public ServerItfHolder ()
  {
  }

  public ServerItfHolder (cache.ServerItf initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = cache.ServerItfHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    cache.ServerItfHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return cache.ServerItfHelper.type ();
  }

}
