package cache;


/**
* cache/ServerItfPOATie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from cache.idl
* vendredi 11 avril 2014 17 h 24 CEST
*/

public class ServerItfPOATie extends ServerItfPOA
{

  // Constructors

  public ServerItfPOATie ( cache.ServerItfOperations delegate ) {
      this._impl = delegate;
  }
  public ServerItfPOATie ( cache.ServerItfOperations delegate , org.omg.PortableServer.POA poa ) {
      this._impl = delegate;
      this._poa      = poa;
  }
  public cache.ServerItfOperations _delegate() {
      return this._impl;
  }
  public void _delegate (cache.ServerItfOperations delegate ) {
      this._impl = delegate;
  }
  public org.omg.PortableServer.POA _default_POA() {
      if(_poa != null) {
          return _poa;
      }
      else {
          return super._default_POA();
      }
  }
  public boolean read (String fileName, String computerId, org.omg.CORBA.StringHolder data) throws cache.FileUnknown, cache.IOError
  {
    return _impl.read(fileName, computerId, data);
  } // read

  public boolean write (String fileName, String computerId, String data) throws cache.FileUnknown, cache.IOError
  {
    return _impl.write(fileName, computerId, data);
  } // write

  private cache.ServerItfOperations _impl;
  private org.omg.PortableServer.POA _poa;

} // class ServerItfPOATie
