package cache;


/**
* cache/ServerItfOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from cache.idl
* vendredi 11 avril 2014 17 h 24 CEST
*/

public interface ServerItfOperations 
{
  boolean read (String fileName, String computerId, org.omg.CORBA.StringHolder data) throws cache.FileUnknown, cache.IOError;
  boolean write (String fileName, String computerId, String data) throws cache.FileUnknown, cache.IOError;
} // interface ServerItfOperations
