package cache;


/**
* cache/WriterItfHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from cache.idl
* vendredi 11 avril 2014 17 h 24 CEST
*/

abstract public class WriterItfHelper
{
  private static String  _id = "IDL:cache/WriterItf:1.0";

  public static void insert (org.omg.CORBA.Any a, cache.WriterItf that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static cache.WriterItf extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (cache.WriterItfHelper.id (), "WriterItf");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static cache.WriterItf read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_WriterItfStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, cache.WriterItf value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static cache.WriterItf narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof cache.WriterItf)
      return (cache.WriterItf)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      cache._WriterItfStub stub = new cache._WriterItfStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static cache.WriterItf unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof cache.WriterItf)
      return (cache.WriterItf)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      cache._WriterItfStub stub = new cache._WriterItfStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
