package cache;


/**
* cache/WriterItfOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from cache.idl
* vendredi 11 avril 2014 17 h 24 CEST
*/

public interface WriterItfOperations 
{
  boolean write (String fileName, String data);
  void fileDataOutOfDate (String fileName);
} // interface WriterItfOperations
