package cache;


/**
* cache/WriterItfPOATie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from cache.idl
* vendredi 11 avril 2014 17 h 24 CEST
*/

public class WriterItfPOATie extends WriterItfPOA
{

  // Constructors

  public WriterItfPOATie ( cache.WriterItfOperations delegate ) {
      this._impl = delegate;
  }
  public WriterItfPOATie ( cache.WriterItfOperations delegate , org.omg.PortableServer.POA poa ) {
      this._impl = delegate;
      this._poa      = poa;
  }
  public cache.WriterItfOperations _delegate() {
      return this._impl;
  }
  public void _delegate (cache.WriterItfOperations delegate ) {
      this._impl = delegate;
  }
  public org.omg.PortableServer.POA _default_POA() {
      if(_poa != null) {
          return _poa;
      }
      else {
          return super._default_POA();
      }
  }
  public boolean write (String fileName, String data)
  {
    return _impl.write(fileName, data);
  } // write

  public void fileDataOutOfDate (String fileName)
  {
    _impl.fileDataOutOfDate(fileName);
  } // fileDataOutOfDate

  private cache.WriterItfOperations _impl;
  private org.omg.PortableServer.POA _poa;

} // class WriterItfPOATie
