package hashtable;


/**
* HashTable/HashTableITFOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from HashTable.idl
* vendredi 4 avril 2014 16 h 11 CEST
*/

public interface HashTableITFOperations 
{
  boolean containKey (String key);
  org.omg.CORBA.Object get (String key);
  boolean put (String key, org.omg.CORBA.Object o);
} // interface HashTableITFOperations
