package hashtable;


/**
* HashTable/HashTableITF.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from HashTable.idl
* vendredi 4 avril 2014 16 h 11 CEST
*/

public interface HashTableITF extends HashTableITFOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface HashTableITF
