package hashtable;

/**
* HashTable/HashTableITFHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from HashTable.idl
* vendredi 4 avril 2014 16 h 11 CEST
*/

public final class HashTableITFHolder implements org.omg.CORBA.portable.Streamable
{
  public HashTableITF value = null;

  public HashTableITFHolder ()
  {
  }

  public HashTableITFHolder (HashTableITF initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = HashTableITFHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    HashTableITFHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return HashTableITFHelper.type ();
  }

}
