package hashtable;


/**
* HashTable/HashTableITFPOATie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from HashTable.idl
* vendredi 4 avril 2014 16 h 11 CEST
*/

public class HashTableITFPOATie extends HashTableITFPOA
{

  // Constructors

  public HashTableITFPOATie ( HashTableITFOperations delegate ) {
      this._impl = delegate;
  }
  public HashTableITFPOATie ( HashTableITFOperations delegate , org.omg.PortableServer.POA poa ) {
      this._impl = delegate;
      this._poa      = poa;
  }
  public HashTableITFOperations _delegate() {
      return this._impl;
  }
  public void _delegate (HashTableITFOperations delegate ) {
      this._impl = delegate;
  }
  public org.omg.PortableServer.POA _default_POA() {
      if(_poa != null) {
          return _poa;
      }
      else {
          return super._default_POA();
      }
  }
  public boolean containKey (String key)
  {
    return _impl.containKey(key);
  } // containKey

  public org.omg.CORBA.Object get (String key)
  {
    return _impl.get(key);
  } // get

  public boolean put (String key, org.omg.CORBA.Object o)
  {
    return _impl.put(key, o);
  } // put

  private HashTableITFOperations _impl;
  private org.omg.PortableServer.POA _poa;

} // class HashTableITFPOATie
