/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculette.h"


void
calculette_1(char *host)
{
	CLIENT *clnt;
	int  *result_1;
	int  calculerdouble_1_arg = 1;
	int  *result_2;

	struct calcul  calculersomme_1_arg;
	calcul.a=1;
	calcul.b=1;

	char * *result_3;
	struct identite  afficheridentite_1_arg;
	identite.prenom="Mag";
	identite.nom="Stellon";

	void  *result_4;
	struct identite  afficherconcatenationidentite_1_arg;
	identite.prenom="Mag";
	identite.nom="Stellon";


	int  *result_5;
	char *nombrecalcul_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, Calculette, v1, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = calculerdouble_1(&calculerdouble_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = calculersomme_1(&calculersomme_1_arg, clnt);
	if (result_2 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_3 = afficheridentite_1(&afficheridentite_1_arg, clnt);
	if (result_3 == (char **) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_4 = afficherconcatenationidentite_1(&afficherconcatenationidentite_1_arg, clnt);
	if (result_4 == (void *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_5 = nombrecalcul_1((void*)&nombrecalcul_1_arg, clnt);
	if (result_5 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	calculette_1 (host);
exit (0);
}
