/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALCULETTE_H_RPCGEN
#define _CALCULETTE_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct calcul {
	int a;
	int b;
};
typedef struct calcul calcul;

struct identite {
	char prenom[250];
	char nom[250];
};
typedef struct identite identite;

#define Calculette 1
#define v1 1

#if defined(__STDC__) || defined(__cplusplus)
#define calculerDouble 1
extern  int * calculerdouble_1(int *, CLIENT *);
extern  int * calculerdouble_1_svc(int *, struct svc_req *);
#define calculerSomme 2
extern  int * calculersomme_1(struct calcul *, CLIENT *);
extern  int * calculersomme_1_svc(struct calcul *, struct svc_req *);
#define afficherIdentite 3
extern  char ** afficheridentite_1(struct identite *, CLIENT *);
extern  char ** afficheridentite_1_svc(struct identite *, struct svc_req *);
#define afficherConcatenationIdentite 4
extern  void * afficherconcatenationidentite_1(struct identite *, CLIENT *);
extern  void * afficherconcatenationidentite_1_svc(struct identite *, struct svc_req *);
#define nombreCalcul 5
extern  int * nombrecalcul_1(void *, CLIENT *);
extern  int * nombrecalcul_1_svc(void *, struct svc_req *);
extern int calculette_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define calculerDouble 1
extern  int * calculerdouble_1();
extern  int * calculerdouble_1_svc();
#define calculerSomme 2
extern  int * calculersomme_1();
extern  int * calculersomme_1_svc();
#define afficherIdentite 3
extern  char ** afficheridentite_1();
extern  char ** afficheridentite_1_svc();
#define afficherConcatenationIdentite 4
extern  void * afficherconcatenationidentite_1();
extern  void * afficherconcatenationidentite_1_svc();
#define nombreCalcul 5
extern  int * nombrecalcul_1();
extern  int * nombrecalcul_1_svc();
extern int calculette_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_calcul (XDR *, calcul*);
extern  bool_t xdr_identite (XDR *, identite*);

#else /* K&R C */
extern bool_t xdr_calcul ();
extern bool_t xdr_identite ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALCULETTE_H_RPCGEN */
