package Calculatrice;


/**
* Calculatrice/ServeurCalculatricePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calculatrice.idl
* vendredi 28 mars 2014 16 h 47 CET
*/

public abstract class ServeurCalculatricePOA extends org.omg.PortableServer.Servant
 implements Calculatrice.ServeurCalculatriceOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("add", new java.lang.Integer (0));
    _methods.put ("sub", new java.lang.Integer (1));
    _methods.put ("mult", new java.lang.Integer (2));
    _methods.put ("div", new java.lang.Integer (3));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // Calculatrice/ServeurCalculatrice/add
       {
         double a = in.read_double ();
         double b = in.read_double ();
         double $result = (double)0;
         $result = this.add (a, b);
         out = $rh.createReply();
         out.write_double ($result);
         break;
       }

       case 1:  // Calculatrice/ServeurCalculatrice/sub
       {
         double a = in.read_double ();
         double b = in.read_double ();
         double $result = (double)0;
         $result = this.sub (a, b);
         out = $rh.createReply();
         out.write_double ($result);
         break;
       }

       case 2:  // Calculatrice/ServeurCalculatrice/mult
       {
         double a = in.read_double ();
         double b = in.read_double ();
         double $result = (double)0;
         $result = this.mult (a, b);
         out = $rh.createReply();
         out.write_double ($result);
         break;
       }

       case 3:  // Calculatrice/ServeurCalculatrice/div
       {
         double a = in.read_double ();
         double b = in.read_double ();
         double $result = (double)0;
         $result = this.div (a, b);
         out = $rh.createReply();
         out.write_double ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Calculatrice/ServeurCalculatrice:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public ServeurCalculatrice _this() 
  {
    return ServeurCalculatriceHelper.narrow(
    super._this_object());
  }

  public ServeurCalculatrice _this(org.omg.CORBA.ORB orb) 
  {
    return ServeurCalculatriceHelper.narrow(
    super._this_object(orb));
  }


} // class ServeurCalculatricePOA
