package Calculatrice;


/**
* Calculatrice/ServeurCalculatriceHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calculatrice.idl
* vendredi 28 mars 2014 16 h 47 CET
*/

abstract public class ServeurCalculatriceHelper
{
  private static String  _id = "IDL:Calculatrice/ServeurCalculatrice:1.0";

  public static void insert (org.omg.CORBA.Any a, Calculatrice.ServeurCalculatrice that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Calculatrice.ServeurCalculatrice extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (Calculatrice.ServeurCalculatriceHelper.id (), "ServeurCalculatrice");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Calculatrice.ServeurCalculatrice read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_ServeurCalculatriceStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Calculatrice.ServeurCalculatrice value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static Calculatrice.ServeurCalculatrice narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Calculatrice.ServeurCalculatrice)
      return (Calculatrice.ServeurCalculatrice)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Calculatrice._ServeurCalculatriceStub stub = new Calculatrice._ServeurCalculatriceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static Calculatrice.ServeurCalculatrice unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Calculatrice.ServeurCalculatrice)
      return (Calculatrice.ServeurCalculatrice)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Calculatrice._ServeurCalculatriceStub stub = new Calculatrice._ServeurCalculatriceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
