package Calculatrice;


/**
* Calculatrice/ServeurCalculatrice.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calculatrice.idl
* vendredi 28 mars 2014 16 h 47 CET
*/

public interface ServeurCalculatrice extends ServeurCalculatriceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ServeurCalculatrice
