package Calculatrice;


/**
* Calculatrice/ServeurCalculatriceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calculatrice.idl
* vendredi 28 mars 2014 16 h 47 CET
*/

public interface ServeurCalculatriceOperations 
{
  double add (double a, double b);
  double sub (double a, double b);
  double mult (double a, double b);
  double div (double a, double b);
} // interface ServeurCalculatriceOperations
